name: plugfox_localstorage
description: Simple cross-platform universal String Key-Value local storage, works on mobile and the web. Has RAM caching. Great for small short values.
version: 0.1.0
homepage: https://plugfox.ru
author: Plague Fox <plugfox@gmail.com>
repository: https://github.com/PlugFox/plugfox_localstorage

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=1.5.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^0.5.3+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: any

flutter:
